### ISSUE TITLE
Mac/Linux version?

### ISSUE THREAD

**Issue by jo-fleck** [ec-jrc/JRC-EUROMOD-software-source-code#1]
From the prerequisites listed [here](https://euromod-web.jrc.ec.europa.eu/sites/default/files/2021-04/EUROMOD%20installation%20and%20configuration%20manual.pdf) I understand that installing the current version of the EUROMOD software requires Windows.

Is there a way to install the software on a Unix based (Mac/Linux) system? If no, are there any plans to make the software compatible with this platform in future releases?

**Comment by ghost** [comment]
Hello,

Thank you for your question.

Yes, installing the current version of EUROMOD software requires Windows. Unfortunately, JRC is not currently planning to make the EUROMOD software available for Unix based (Mac/Linux) systems.

Thank you!
Sorry for the inconveniences.

**Comment by jo-fleck** [comment]
Thanks for the clarification @estvazquez !
